/*
 * Copyright © 2026 Metreeca srl
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Response status middleware.
 *
 * Admits only 2xx responses from the wrapped {@link Fetch} implementation, reporting error responses and transport
 * failures alike as {@link Problem | problems}.
 *
 * **Usage**
 *
 * ```typescript
 * import { createFetch, NotFound } from "@metreeca/http";
 * import { success } from "@metreeca/http/success";
 *
 * const client = createFetch(success()); // rejects unless response.ok
 *
 * try {
 *
 *   const response = await client("https://api.example.com/data");
 *
 * } catch ( problem ) { // a Problem, whatever went wrong
 *
 *   if ( problem.status === NotFound ) { // handle a missing resource
 *   }
 *
 * }
 * ```
 *
 * @module
 *
 * @see {@link https://www.rfc-editor.org/rfc/rfc9457 RFC 9457 - Problem Details for HTTP APIs}
 */

import { isError, type Value } from "@metreeca/core";
import { immutable } from "@metreeca/core/structures";
import type { Fetch, Middleware } from "../index.js";


/**
 * Problem details for HTTP APIs.
 *
 * Portable description of an error condition, as defined by RFC 9457, which obsoletes RFC 7807. Every field is
 * optional, so a report carries as much detail as its source provides: `type` and `title` classify the problem,
 * `status`, `detail`, and `instance` pin it to a specific occurrence, and `report` conveys machine-readable data
 * for automated handling.
 *
 * {@link success} reports failed exchanges in this shape, so a client assembled with it surfaces transport failures
 * and error responses alike as problem details.
 *
 * @example
 *
 * ```typescript
 * const problem: Problem = {
 *   status: 404,
 *   title: "Not Found",
 *   detail: "Resource /api/users/123 does not exist",
 *   instance: "/api/users/123",
 *   report: { timestamp: "2025-12-02T10:30:00Z" }
 * };
 * ```
 *
 * @see {@link https://www.rfc-editor.org/rfc/rfc9457 RFC 9457 - Problem Details for HTTP APIs}
 */
export type Problem = {

	/**
	 * Short, human-readable summary of the problem type.
	 *
	 * Should be the same for all occurrences of this problem type, for example `Payment Required` or `Not Found`.
	 */
	readonly title?: string;

	/**
	 * URI reference identifying the problem type.
	 *
	 * @defaultValue "about:blank"
	 */
	readonly type?: string;

	/**
	 * URI reference identifying the specific occurrence of the problem.
	 */
	readonly instance?: string;

	/**
	 * HTTP status code generated by the origin server.
	 */
	readonly status?: number;

	/**
	 * Human-readable explanation specific to this occurrence of the problem.
	 */
	readonly detail?: string;

	/**
	 * Machine-readable details about this occurrence of the problem.
	 *
	 * An RFC 9457 extension member, shaped as the reporting party requires, for instance a validation trace or a
	 * diagnostic payload consumers may branch on.
	 */
	readonly report?: Value;

}


/**
 * Creates a middleware admitting only 2xx responses, reporting failures as {@link Problem | problems}.
 *
 * Decorates a {@link Fetch} implementation with one reporting every failure as a single structured exception, so that
 * callers await a usable response rather than inspecting `response.ok` at each call site:
 *
 * - **Response is `ok`** (2xx `status`): the promise resolves with the response unchanged
 * - **Response is not `ok`** (non-2xx `status`): the promise rejects with a {@link Problem} carrying the response
 *   `status` and its `statusText` as `detail`, plus the body as `report` when the `Content-Type` allows it to be read:
 *   - `text/plain`: the body as text
 *   - JSON-based media types, for example `application/json`, `application/ld+json` or `application/problem+json`: the
 *     parsed JSON payload
 *   - other media types, or a body that fails to parse: no `report`
 * - **The wrapped implementation rejects with an `Error`** (network failures, timeouts, CORS denials): the promise
 *   rejects with a {@link Problem} carrying `status` 0 and a rendering of the error as `detail`
 * - **The wrapped implementation rejects with any other value** (typically a {@link Problem} raised by an inner
 *   layer): the value is relayed unchanged
 *
 * Problems reported by this middleware are {@link immutable}, so a handler may pass one on without guarding against
 * later mutation.
 *
 * > [!NOTE]
 * > The middleware is idempotent: applying it more than once to the same chain is harmless, as a {@link Problem}
 * > raised by an inner layer is relayed unchanged rather than reported again as a transport failure.
 *
 * @returns A {@link Middleware} wrapping a {@link Fetch} implementation with one reporting every failed exchange as an
 *     immutable {@link Problem}
 *
 * @see {@link https://www.rfc-editor.org/rfc/rfc9110#section-15.3 RFC 9110 § 15.3 - Successful 2xx}
 * @see {@link https://www.rfc-editor.org/rfc/rfc9457 RFC 9457 - Problem Details for HTTP APIs}
 */
export function success(): Middleware {

	return fetch => (input, init) => fetch(input, init)

		.catch(error => { // relay problems raised by an inner layer, converting only genuine transport failures

			if ( isError(error) ) {

				throw immutable<Problem>({

					status: 0,
					detail: `fetch error <${error}>`

				});

			} else {

				throw error;

			}

		})

		.then(response => {

			if ( response.ok ) {

				return response;

			} else {

				const mime = response.headers.get("Content-Type");

				if ( mime?.match(/^text\/plain\b/i) ) {

					return response.text()

						.catch(_ => {

							throw immutable<Problem>({

								status: response.status,
								detail: response.statusText

							});

						})

						.then(value => {

							throw immutable<Problem>({

								status: response.status,
								detail: response.statusText,

								report: value

							});

						});

				} else if ( mime?.match(/[\/+]json\b/i) ) {

					return response.json()

						.catch(_ => {

							throw immutable<Problem>({

								status: response.status,
								detail: response.statusText

							});

						})

						.then(value => {

							throw immutable<Problem>({

								status: response.status,
								detail: response.statusText,

								report: value

							});

						});

				} else {

					throw immutable<Problem>({

						status: response.status,
						detail: response.statusText

					});

				}

			}

		});

}
